export const engKeys = [
    { id: 1, name: "Backquote", value: "`", class: "key" },
    { id: 2, name: "Digit1", value: "1", class: "key" },
    { id: 3, name: "Digit2", value: "2", class: "key" },
    { id: 4, name: "Digit3", value: "3", class: "key" },
    { id: 5, name: "Digit4", value: "4", class: "key" },
    { id: 6, name: "Digit5", value: "5", class: "key" },
    { id: 7, name: "Digit6", value: "6", class: "key" },
    { id: 8, name: "Digit7", value: "7", class: "key" },
    { id: 9, name: "Digit8", value: "8", class: "key" },
    { id: 10, name: "Digit9", value: "9", class: "key" },
    { id: 11, name: "Digit0", value: "0", class: "key" },
    { id: 12, name: "Minus", value: "-", class: "key" },
    { id: 13, name: "Equal", value: "=", class: "key" },
    { id: 65, name: "Backspace", value: "Backspace", class: "key double" },
    { id: 14, name: "Tab", value: "Tab", class: "key double" },

    { id: 15, name: "KeyQ", value: "Q", class: "key" },
    { id: 16, name: "KeyW", value: "W", class: "key" },
    { id: 17, name: "KeyE", value: "E", class: "key" },
    { id: 18, name: "KeyR", value: "R", class: "key" },
    { id: 19, name: "KeyT", value: "T", class: "key" },
    { id: 20, name: "KeyY", value: "Y", class: "key" },
    { id: 21, name: "KeyU", value: "U", class: "key" },
    { id: 22, name: "KeyI", value: "I", class: "key" },
    { id: 23, name: "KeyO", value: "O", class: "key" },
    { id: 24, name: "KeyP", value: "P", class: "key" },

    { id: 25, name: "BracketLeft", value: "[", class: "key" },
    { id: 26, name: "BracketRight", value: "]", class: "key" },
    { id: 27, name: "Delete", value: "Delete", class: "key" },
    { id: 28, name: "CapsLock", value: "CapsLock", class: "key double" },

    { id: 29, name: "KeyA", value: "A", class: "key" },
    { id: 30, name: "KeyS", value: "S", class: "key" },
    { id: 31, name: "KeyD", value: "D", class: "key" },
    { id: 32, name: "KeyF", value: "F", class: "key" },
    { id: 33, name: "KeyG", value: "G", class: "key" },
    { id: 34, name: "KeyH", value: "H", class: "key" },
    { id: 35, name: "KeyJ", value: "J", class: "key" },
    { id: 36, name: "KeyK", value: "K", class: "key" },
    { id: 37, name: "KeyL", value: "L", class: "key" },
    { id: 38, name: "Semicolon", value: ";", class: "key" },
    { id: 40, name: "Quote", value: "'", class: "key" },
    { id: 41, name: "Backslash", value: "\\", class: "key" },
    { id: 42, name: "Enter", value: "Enter", class: "key double" },
    { id: 43, name: "ShiftLeft", value: "Shift", class: "key double" },
    { id: 44, name: "KeyZ", value: "Z", class: "key" },
    { id: 45, name: "KeyX", value: "X", class: "key" },
    { id: 56, name: "KeyC", value: "C", class: "key" },
    { id: 47, name: "KeyV", value: "V", class: "key" },
    { id: 48, name: "KeyB", value: "B", class: "key" },
    { id: 49, name: "KeyN", value: "N", class: "key" },
    { id: 50, name: "KeyM", value: "M", class: "key" },
    { id: 51, name: "Comma", value: ",", class: "key" },
    { id: 52, name: "Period", value: ".", class: "key" },
    { id: 53, name: "Slash", value: "/", class: "key" },
    { id: 54, name: "ArrowUp", value: "Up", class: "key" },
    { id: 55, name: "ShiftRight", value: "Shift", class: "key double" },
    { id: 56, name: "ControlLeft", value: "Ctrl", class: "key double" },
    { id: 57, name: "MetaLeft", value: "Win", class: "key" },
    { id: 58, name: "AltLeft", value: "Alt", class: "key" },
    { id: 59, name: "Space", value: "Space", class: "key space-button" },
    { id: 60, name: "AltRight", value: "Alt", class: "key" },
    { id: 61, name: "ControlRight", value: "Ctrl", class: "key double" },
    { id: 62, name: "ArrowLeft", value: "Left", class: "key" },
    { id: 63, name: "ArrowDown", value: "Down", class: "key" },
    { id: 64, name: "ArrowRight", value: "Right", class: "key" },
];

export const ruKeys = [
    { id: 1, name: "Backquote", value: "`", class: "key" },
    { id: 2, name: "Digit1", value: "1", class: "key" },
    { id: 3, name: "Digit2", value: "2", class: "key" },
    { id: 4, name: "Digit3", value: "3", class: "key" },
    { id: 5, name: "Digit4", value: "4", class: "key" },
    { id: 6, name: "Digit5", value: "5", class: "key" },
    { id: 7, name: "Digit6", value: "6", class: "key" },
    { id: 8, name: "Digit7", value: "7", class: "key" },
    { id: 9, name: "Digit8", value: "8", class: "key" },
    { id: 10, name: "Digit9", value: "9", class: "key" },
    { id: 11, name: "Digit0", value: "0", class: "key" },
    { id: 12, name: "Minus", value: "-", class: "key" },
    { id: 13, name: "Equal", value: "=", class: "key" },
    { id: 65, name: "Backspace", value: "Backspace", class: "key double" },
    { id: 14, name: "Tab", value: "Tab", class: "key double" },

    { id: 15, name: "KeyQ", value: "Й", class: "key" },
    { id: 16, name: "KeyW", value: "Ц", class: "key" },
    { id: 17, name: "KeyE", value: "У", class: "key" },
    { id: 18, name: "KeyR", value: "К", class: "key" },
    { id: 19, name: "KeyT", value: "Е", class: "key" },
    { id: 20, name: "KeyY", value: "Н", class: "key" },
    { id: 21, name: "KeyU", value: "Г", class: "key" },
    { id: 22, name: "KeyI", value: "Ш", class: "key" },
    { id: 23, name: "KeyO", value: "Щ", class: "key" },
    { id: 24, name: "KeyP", value: "З", class: "key" },

    { id: 25, name: "BracketLeft", value: "Х", class: "key" },
    { id: 26, name: "BracketRight", value: "Ъ", class: "key" },
    { id: 27, name: "Delete", value: "Delete", class: "key" },
    { id: 28, name: "CapsLock", value: "CapsLock", class: "key double" },

    { id: 29, name: "KeyA", value: "Ф", class: "key" },
    { id: 30, name: "KeyS", value: "Ы", class: "key" },
    { id: 31, name: "KeyD", value: "В", class: "key" },
    { id: 32, name: "KeyF", value: "А", class: "key" },
    { id: 33, name: "KeyG", value: "П", class: "key" },
    { id: 34, name: "KeyH", value: "Р", class: "key" },
    { id: 35, name: "KeyJ", value: "О", class: "key" },
    { id: 36, name: "KeyK", value: "Л", class: "key" },
    { id: 37, name: "KeyL", value: "Д", class: "key" },

    { id: 38, name: "Semicolon", value: "Ж", class: "key" },
    { id: 40, name: "Quote", value: "Э", class: "key" },
    { id: 41, name: "Backslash", value: "\\", class: "key" },
    { id: 42, name: "Enter", value: "Enter", class: "key double" },
    { id: 43, name: "ShiftLeft", value: "Shift", class: "key double" },
    { id: 44, name: "KeyZ", value: "Я", class: "key" },
    { id: 45, name: "KeyX", value: "Ч", class: "key" },
    { id: 56, name: "KeyC", value: "С", class: "key" },
    { id: 47, name: "KeyV", value: "М", class: "key" },
    { id: 48, name: "KeyB", value: "И", class: "key" },
    { id: 49, name: "KeyN", value: "Т", class: "key" },
    { id: 50, name: "KeyM", value: "Ь", class: "key" },
    { id: 51, name: "Comma", value: "Б", class: "key" },
    { id: 52, name: "Period", value: "Ю", class: "key" },
    { id: 53, name: "Slash", value: ".", class: "key" },
    { id: 54, name: "ArrowUp", value: "Up", class: "key" },
    { id: 55, name: "ShiftRight", value: "Shift", class: "key double" },
    { id: 56, name: "ControlLeft", value: "Ctrl", class: "key double" },
    { id: 57, name: "MetaLeft", value: "Win", class: "key" },
    { id: 58, name: "AltLeft", value: "Alt", class: "key" },
    { id: 59, name: "Space", value: "Space", class: "key space-button" },
    { id: 60, name: "AltRight", value: "Alt", class: "key" },
    { id: 61, name: "ControlRight", value: "Ctrl", class: "key double" },
    { id: 62, name: "ArrowLeft", value: "Left", class: "key" },
    { id: 63, name: "ArrowDown", value: "Down", class: "key" },
    { id: 64, name: "ArrowRight", value: "Right", class: "key" },
];

